[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "www_Day_Dream"
name = "MultiplayerModRestrictor"
description = "A Last Train Outta' Wormtown plugin that facilitates other plugins restricting multiplayer access by mod versioning."
websiteUrl = "https://github.com/wwwDayDream/MultiplayerModRestrictor"
containsNsfwContent = false

[package.dependencies]
BepInEx_Wormtown-BepInExPack = "5.4.22"

[build]
icon = "icon.png"
readme = "./TS-README.md"
outdir = "../"

[[build.copy]]
source = "../LICENSE"
target = "/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../MultiplayerModRestrictor/bin/Release/netstandard2.1/wwwDayDream.MultiplayerModRestrictor.dll"
target = "/BepInEx/plugins/wwwDayDream.MultiplayerModRestrictor/"

[publish]
communities = [ "last-train-outta-wormtown" ]
categories = [ "libraries" ]
