[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "www_Day_Dream"
name = "MultiplayerModRestrictor"
description = ""
websiteUrl = ""
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = ""

[build]
icon = "icon.png"
readme = "./TS-README.md"
outdir = "../dist"

[[build.copy]]
source = "../LICENSE"
target = "/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../bin/Release/netstandard2.1/wwwDayDream.MultiplayerModRestrictor.dll"
target = "/BepInEx/plugins/wwwDayDream.MultiplayerModRestrictor/"

[publish]
communities = [ "last-train-outta-wormtown" ]
categories = [ "libraries" ]
